version: "3"
services:

  web:
    build:
      context: ../
      dockerfile: docker/http_server.dockerfile
    ports:
      - "9000:80"

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: pr2
      MYSQL_USER: pr2-user
      MYSQL_PASSWORD: pr2-user-password
      MYSQL_ROOT_PASSWORD: root-user-password

  liquibase:
    image: webdevops/liquibase
    command: /scripts/init-liquibase.sh
    environment:
      LIQUIBASE_URL: jdbc:mysql://mysql/pr2
      LIQUIBASE_USERNAME: root
      LIQUIBASE_PASSWORD: root-user-password
      LIQUIBASE_CHANGELOG: /liquibase/changelog.yaml
    volumes:
      - ../liquibase:/liquibase
      - ./:/scripts
    depends_on:
      - mysql
    restart: 'no'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
