version: "3"
services:
  web:
    build:
      context: ../
      dockerfile: docker/http_server.dockerfile
    ports:
      - "8080:80"
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: pr2
      MYSQL_USER: pr2-user
      MYSQL_PASSWORD: pr2-user-password
      MYSQL_ROOT_PASSWORD: root-user-password 